export const COUNTRY_MAP: Record<string, string> = {
  US: "USA",
  BR: "Brazil",
  KR: "South Korea",
  GB: "UK",
  FR: "France",
  JP: "Japan",
  CA: "Canada",
  MX: "Mexico",
  AR: "Argentina",
  CO: "Colombia",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  PT: "Portugal",
  IE: "Ireland",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  NL: "Netherlands",
  CN: "China",
  IN: "India",
  HK: "Hong Kong",
  TH: "Thailand",
  AU: "Australia",
  NZ: "New Zealand",
  TR: "Turkey",
  IL: "Israel",
  ZA: "South Africa",
  NG: "Nigeria",
};
